Repository PlaceholderAPI/PlaceholderAPI, pull requests merged in 2021-12, with the labels that each got.

#747 Update Dependencies of PlaceholderAPI
  build.gradle
Labels: Target: Code, Type: Bugfix

#749 nullable annotation placeholderhook
  src/main/java/me/clip/placeholderapi/PlaceholderHook.java
Labels: Type: Enhancement, Target: Code

#687 Add Java Version to /papi dump command
  src/main/java/me/clip/placeholderapi/commands/impl/local/CommandDump.java
Labels: Type: Enhancement

#758 Merge Development into master
  build.gradle
Labels: Type: Enhancement

#717 Include version in registration message and other QOL changes
  build.gradle
  src/main/java/me/clip/placeholderapi/events/ExpansionRegisterEvent.java
  src/main/java/me/clip/placeholderapi/events/ExpansionUnregisterEvent.java
  src/main/java/me/clip/placeholderapi/events/ExpansionsLoadedEvent.java
  src/main/java/me/clip/placeholderapi/expansion/Cacheable.java
  src/main/java/me/clip/placeholderapi/expansion/Cleanable.java
  src/main/java/me/clip/placeholderapi/expansion/Configurable.java
  src/main/java/me/clip/placeholderapi/expansion/Relational.java
  src/main/java/me/clip/placeholderapi/expansion/Taskable.java
  src/main/java/me/clip/placeholderapi/expansion/manager/LocalExpansionManager.java
Labels: Type: Enhancement

#752 1.18 + Gradle Updates
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  src/main/java/me/clip/placeholderapi/expansion/NMSVersion.java
Labels: Type: Enhancement

#667 Fix issue with invalid placeholder pattern lowercasing text
  src/main/java/me/clip/placeholderapi/PlaceholderAPI.java
  src/main/java/me/clip/placeholderapi/PlaceholderAPIPlugin.java
  src/main/java/me/clip/placeholderapi/PlaceholderHook.java
  src/main/java/me/clip/placeholderapi/expansion/PlaceholderExpansion.java
  src/main/java/me/clip/placeholderapi/expansion/cloud/CloudExpansion.java
  src/main/java/me/clip/placeholderapi/listeners/ServerLoadEventListener.java
  src/main/java/me/clip/placeholderapi/replacer/CharsReplacer.java
  src/main/java/me/clip/placeholderapi/util/Format.java
Labels: Type: Bugfix
