Repository PlaceholderAPI/PlaceholderAPI, pull requests merged in 2023-02, with the labels that each got.

#873 Fix inconsistent parsing command behaviour
  src/main/java/me/clip/placeholderapi/commands/impl/local/CommandParse.java
Labels: Target: Code, Type: Bugfix

#869 remove the eCloud toggle command
  src/main/java/me/clip/placeholderapi/commands/impl/cloud/CommandECloud.java
  src/main/java/me/clip/placeholderapi/commands/impl/cloud/CommandECloudToggle.java
Labels: Type: Enhancement

#919 update vault placeholders
  Placeholders.md
Labels: Type: Enhancement, Target: Wiki

#870 [Wiki] Add question about PlaceholderExpansion
  FAQ.md
Labels: Target: Wiki
